package com.example.testcompanynew.model

data class Promotion(
    val AppId: Int,
    val CampaignId: Int,
    val CampaignName: String,
    val Event: Event,
    val EventEndDt: String,
    val EventEndTime: String,
    val EventStartDt: String,
    val EventStartTime: String,
    val IsABPinned: Boolean,
    val IsCancel: Boolean,
    val IsDeleted: Boolean,
    val IsEdit: Boolean,
    val IsEdited: Boolean,
    val ListId: Int,
    val NotificationMessage: String,
    val PageNumber: Int,
    val PageSize: Int,
    val Priority: Int,
    val PromotionCategory: String,
    val PromotionId: Int,
    val PromotionType: String,
    val PromotionTypeId: Int,
    val RowCounter: Int,
    val SendNotification: Boolean,
    val SortNumber: Int,
    val StatusId: Int,
    val StatusName: String,
    val StoreId: Int,
    val TargetContent: String,
    val TargetContentType: String,
    val Title: String,
    val Url: String,
    val UserId: Int
)